
import { Property, PropertyType, BusinessType, Testimonial } from './types';

export const PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Chácara Locação',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 2000,
    location: { neighborhood: 'Jardim Europa', city: 'São João da Boa Vista' },
    features: { bedrooms: 4, bathrooms: 6, parkingSpots: 4, area: 550 },
    imageUrl: '/images/imoveis/img1.jpg',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Apartamento Duplex Executive',
    type: PropertyType.APARTAMENTO,
    businessType: BusinessType.COMPRAR,
    price: 1200000,
    location: { neighborhood: 'Centro', city: 'São João da Boa Vista' },
    features: { bedrooms: 3, bathrooms: 4, parkingSpots: 2, area: 180 },
    imageUrl: '/images/imoveis/img2.jpg',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Chácara Locação',
    type: PropertyType.CASA,
    businessType: BusinessType.ALUGAR,
    price: 2000,
    location: { neighborhood: 'Vila Conceição', city: 'São João da Boa Vista' },
    features: { bedrooms: 3, bathrooms: 3, parkingSpots: 2, area: 220 },
    imageUrl: '/images/imoveis/img3.jpg',
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Chácara Locação',
    type: PropertyType.COBERTURA,
    businessType: BusinessType.COMPRAR,
    price: 2800000,
    location: { neighborhood: 'Vila Conceição', city: 'São João da Boa Vista' },
    features: { bedrooms: 4, bathrooms: 5, parkingSpots: 3, area: 340 },
    imageUrl: '/images/imoveis/img4.jpg',
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Terreno Centro Locação',
    type: PropertyType.APARTAMENTO,
    businessType: BusinessType.ALUGAR,
    price: 6000,
    location: { neighborhood: 'Centro', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 2, parkingSpots: 1, area: 120 },
    imageUrl: '/images/imoveis/img5.jpg',
    isFeatured: true,
  },
  {
    id: '6',
    title: 'Chácara Aluguel',
    type: PropertyType.CASA,
    businessType: BusinessType.ALUGAR,
    price: 2600,
    location: { neighborhood: 'Jardim dos Ypê III', city: 'São João da Boa Vista' },
    features: { bedrooms: 4, bathrooms: 4, parkingSpots: 3, area: 380 },
    imageUrl: '/images/imoveis/img6.jpg',
    isFeatured: true,
  },
  {
    id: '7',
    title: 'Chácara Cantinho da Paz',
    type: PropertyType.APARTAMENTO,
    businessType: BusinessType.ALUGAR,
    price: 1000,
    location: { neighborhood: 'Estrada da Serra da Paulista', city: 'São João da Boa Vista' },
    features: { bedrooms: 1, bathrooms: 1, parkingSpots: 1, area: 60 },
    imageUrl: '/images/imoveis/img7.jpg',
    isFeatured: true,
  },
  {
    id: '8',
    title: 'Casa de Campo Exclusiva',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 3200000,
    location: { neighborhood: 'Campo Verde', city: 'São João da Boa Vista' },
    features: { bedrooms: 5, bathrooms: 4, parkingSpots: 6, area: 1200 },
    imageUrl: '/images/imoveis/img8.jpg',
    isFeatured: true,
  },
  {
    id: '9',
    title: 'Apartamento Luxo Centro',
    type: PropertyType.APARTAMENTO,
    businessType: BusinessType.COMPRAR,
    price: 950000,
    location: { neighborhood: 'Centro', city: 'São João da Boa Vista' },
    features: { bedrooms: 3, bathrooms: 2, parkingSpots: 2, area: 140 },
    imageUrl: 'https://picsum.photos/id/110/800/600',
    isFeatured: true,
  },
  {
    id: '10',
    title: 'Loft Industrial',
    type: PropertyType.APARTAMENTO,
    businessType: BusinessType.COMPRAR,
    price: 780000,
    location: { neighborhood: 'Bairro das Industrias', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 2, parkingSpots: 1, area: 110 },
    imageUrl: 'https://picsum.photos/id/111/800/600',
    isFeatured: false,
  },
  {
    id: '11',
    title: 'Sítio à Venda',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 1500000,
    location: { neighborhood: 'Zona Rural', city: 'São João da Boa Vista' },
    features: { bedrooms: 4, bathrooms: 3, parkingSpots: 4, area: 5000 },
    imageUrl: 'https://picsum.photos/id/112/800/600',
    isFeatured: false,
  },
  {
    id: '12',
    title: 'Terreno Alto Padrão',
    type: PropertyType.TERRENO,
    businessType: BusinessType.COMPRAR,
    price: 600000,
    location: { neighborhood: 'Alto do Vale', city: 'São João da Boa Vista' },
    features: { bedrooms: 0, bathrooms: 0, parkingSpots: 0, area: 800 },
    imageUrl: 'https://picsum.photos/id/113/800/600',
    isFeatured: false,
  },
  {
    id: '13',
    title: 'Cobertura Vista Mar',
    type: PropertyType.COBERTURA,
    businessType: BusinessType.COMPRAR,
    price: 4200000,
    location: { neighborhood: 'Praia Bela', city: 'Ubatuba' },
    features: { bedrooms: 4, bathrooms: 4, parkingSpots: 3, area: 380 },
    imageUrl: 'https://picsum.photos/id/114/800/600',
    isFeatured: true,
  },
  {
    id: '14',
    title: 'Casa Familiar',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 850000,
    location: { neighborhood: 'Jardim das Flores', city: 'São João da Boa Vista' },
    features: { bedrooms: 3, bathrooms: 2, parkingSpots: 2, area: 220 },
    imageUrl: 'https://picsum.photos/id/115/800/600',
    isFeatured: false,
  },
  {
    id: '15',
    title: 'Ponto Comercial',
    type: PropertyType.COMERCIAL,
    businessType: BusinessType.COMPRAR,
    price: 2000000,
    location: { neighborhood: 'Avenida Principal', city: 'São João da Boa Vista' },
    features: { bedrooms: 0, bathrooms: 2, parkingSpots: 6, area: 400 },
    imageUrl: 'https://picsum.photos/id/116/800/600',
    isFeatured: false,
  },
  {
    id: '16',
    title: 'Sobrado Reformado',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 1250000,
    location: { neighborhood: 'Vila Nova', city: 'São João da Boa Vista' },
    features: { bedrooms: 4, bathrooms: 3, parkingSpots: 2, area: 260 },
    imageUrl: 'https://picsum.photos/id/117/800/600',
    isFeatured: false,
  },
  {
    id: '17',
    title: 'Apartamento Garden',
    type: PropertyType.APARTAMENTO,
    businessType: BusinessType.COMPRAR,
    price: 1350000,
    location: { neighborhood: 'Residencial Park', city: 'São João da Boa Vista' },
    features: { bedrooms: 3, bathrooms: 3, parkingSpots: 2, area: 160 },
    imageUrl: 'https://picsum.photos/id/118/800/600',
    isFeatured: true,
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Ana Paula Mendes',
    city: 'São João da Boa Vista',
    text: 'A Renata foi essencial na compra do nosso primeiro imóvel. Sua visão técnica e segurança jurídica nos deram a tranquilidade que precisávamos para um investimento tão alto.',
  },
  {
    id: '2',
    name: 'Roberto Silveira',
    city: 'Campinas',
    text: 'Atendimento impecável e extremamente profissional. Encontramos o imóvel perfeito graças à curadoria estratégica da Renata.',
  }
];
