
import { Property, PropertyType, BusinessType, Testimonial } from './types';

export const PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Casa São Benedito',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 360000,
    location: { neighborhood: 'São Benedito', city: 'São João da Boa Vista' },
    features: { bedrooms: 4, bathrooms: 3 },
    imageUrl: '/images/imoveis/imovel-1-1.png',
    images: [
      '/images/imoveis/imovel-1-1.png',
      '/images/imoveis/imovel-1-2.png',
      '/images/imoveis/imovel-1-3.png',
      '/images/imoveis/imovel-1-4.png',
      '/images/imoveis/imovel-1-5.png',
      '/images/imoveis/imovel-1-6.png',
      '/images/imoveis/imovel-1-7.png',
      '/images/imoveis/imovel-1-8.png',
      '/images/imoveis/imovel-1-9.png',
      '/images/imoveis/imovel-1-10.png'
    ],
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Casa Jardim Tulipas',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 485000,
    location: { neighborhood: 'Jardim Tulipas', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 2, parkingSpots: 2, area: 160 },
    imageUrl: '/images/imoveis/imovel-2-1.png',
    images: [
      '/images/imoveis/imovel-2-1.png',
      '/images/imoveis/imovel-2-2.png',
      '/images/imoveis/imovel-2-3.png',
      '/images/imoveis/imovel-2-4.png',
      '/images/imoveis/imovel-2-5.png',
      '/images/imoveis/imovel-2-6.png',
      '/images/imoveis/imovel-2-7.png',
      '/images/imoveis/imovel-2-8.png',
      '/images/imoveis/imovel-2-9.png',
      '/images/imoveis/imovel-2-10.png',
      '/images/imoveis/imovel-2-11.png',
      '/images/imoveis/imovel-2-12.png'
    ],
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Casa Jardim Aurora',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 320000,
    location: { neighborhood: 'Jardim Aurora', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 1, parkingSpots: 1, area: 200 },
    imageUrl: '/images/imoveis/imovel-3-1.png',
    images: [
      '/images/imoveis/imovel-3-1.png',
      '/images/imoveis/imovel-3-2.png',
      '/images/imoveis/imovel-3-3.png',
      '/images/imoveis/imovel-3-4.png',
      '/images/imoveis/imovel-3-5.png',
      '/images/imoveis/imovel-3-6.png',
      '/images/imoveis/imovel-3-7.png',
      '/images/imoveis/imovel-3-8.png',
      '/images/imoveis/imovel-3-9.png',
      '/images/imoveis/imovel-3-10.png',
      '/images/imoveis/imovel-3-11.png',
      '/images/imoveis/imovel-3-12.png'
    ],
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Casa Jardim Aurora',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 335000,
    location: { neighborhood: 'Jardim Aurora', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 1, parkingSpots: 1, area: 200 },
    imageUrl: '/images/imoveis/imovel-4-1.jpg',
    images: [
      '/images/imoveis/imovel-4-1.jpg',
      '/images/imoveis/imovel-4-2.png',
      '/images/imoveis/imovel-4-3.png',
      '/images/imoveis/imovel-4-4.png',
      '/images/imoveis/imovel-4-5.png',
      '/images/imoveis/imovel-4-6.png',
      '/images/imoveis/imovel-4-7.png',
      '/images/imoveis/imovel-4-8.jpg',
      '/images/imoveis/imovel-4-9.png',
      '/images/imoveis/imovel-4-10.png',
      '/images/imoveis/imovel-4-11.jpg',
      '/images/imoveis/imovel-4-12.png',
      '/images/imoveis/imovel-4-13.png'
    ],
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Casa Jardim Yolanda',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 280000,
    location: { neighborhood: 'Jardim Yolanda', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 1 },
    imageUrl: '/images/imoveis/imovel-5-1.jpg',
    images: [
      '/images/imoveis/imovel-5-1.jpg',
      '/images/imoveis/imovel-5-2.jpg',
      '/images/imoveis/imovel-5-3.jpg',
      '/images/imoveis/imovel-5-4.png',
      '/images/imoveis/imovel-5-5.jpg',
      '/images/imoveis/imovel-5-6.png',
      '/images/imoveis/imovel-5-7.jpg',
      '/images/imoveis/imovel-5-8.jpg',
      '/images/imoveis/imovel-5-9.jpg',
      '/images/imoveis/imovel-5-10.jpg',
      '/images/imoveis/imovel-5-11.jpg'
    ],
    isFeatured: true,
  },
  {
    id: '6',
    title: 'Casa São Benedito',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 360000,
    location: { neighborhood: 'São Benedito', city: 'São João da Boa Vista' },
    features: { bedrooms: 3, bathrooms: 2, parkingSpots: 2 },
    imageUrl: '/images/imoveis/imovel-6-1.jpg',
    images: [
      '/images/imoveis/imovel-6-1.jpg',
      '/images/imoveis/imovel-6-2.png',
      '/images/imoveis/imovel-6-3.png',
      '/images/imoveis/imovel-6-4.png',
      '/images/imoveis/imovel-6-5.png',
      '/images/imoveis/imovel-6-6.jpg',
      '/images/imoveis/imovel-6-7.jpg',
      '/images/imoveis/imovel-6-8.jpg',
      '/images/imoveis/imovel-6-9.png',
      '/images/imoveis/imovel-6-10.png',
      '/images/imoveis/imovel-6-11.png',
      '/images/imoveis/imovel-6-12.png',
      '/images/imoveis/imovel-6-13.png',
      '/images/imoveis/imovel-6-14.png',
      '/images/imoveis/imovel-6-15.png',
      '/images/imoveis/imovel-6-16.jpg',
      '/images/imoveis/imovel-6-17.png',
      '/images/imoveis/imovel-6-18.png',
      '/images/imoveis/imovel-6-19.png'
    ],
    isFeatured: true,
  },
  {
    id: '7',
    title: 'Casa Vila Rica',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 600000,
    location: { neighborhood: 'Vila Rica', city: 'São João da Boa Vista' },
    features: { bedrooms: 3, bathrooms: 2, parkingSpots: 2, area: 290 },
    imageUrl: '/images/imoveis/imovel-7-1.jpg',
    images: [
      '/images/imoveis/imovel-7-1.jpg',
      '/images/imoveis/imovel-7-2.png',
      '/images/imoveis/imovel-7-3.jpg',
      '/images/imoveis/imovel-7-4.jpg',
      '/images/imoveis/imovel-7-5.jpg',
      '/images/imoveis/imovel-7-6.jpg',
      '/images/imoveis/imovel-7-7.jpg',
      '/images/imoveis/imovel-7-8.jpg',
      '/images/imoveis/imovel-7-9.jpg',
      '/images/imoveis/imovel-7-10.jpg',
      '/images/imoveis/imovel-7-11.jpg',
      '/images/imoveis/imovel-7-12.jpg',
      '/images/imoveis/imovel-7-13.jpg',
      '/images/imoveis/imovel-7-14.jpg',
      '/images/imoveis/imovel-7-15.jpg',
      '/images/imoveis/imovel-7-16.jpg'
    ],
    isFeatured: true,
  },
  {
    id: '8',
    title: 'Casa Jardim Tulipas',
    type: PropertyType.CASA,
    businessType: BusinessType.COMPRAR,
    price: 380000,
    location: { neighborhood: 'Jardim Tulipas', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 1, parkingSpots: 3 },
    imageUrl: '/images/imoveis/imovel-8-1.jpg',
    images: [
      '/images/imoveis/imovel-8-1.jpg',
      '/images/imoveis/imovel-8-2.jpg',
      '/images/imoveis/imovel-8-3.jpg',
      '/images/imoveis/imovel-8-4.jpg',
      '/images/imoveis/imovel-8-5.jpg',
      '/images/imoveis/imovel-8-6.jpg',
      '/images/imoveis/imovel-8-7.jpg',
      '/images/imoveis/imovel-8-8.jpg',
      '/images/imoveis/imovel-8-9.jpg',
      '/images/imoveis/imovel-8-10.jpg',
      '/images/imoveis/imovel-8-11.jpg',
      '/images/imoveis/imovel-8-12.jpg',
      '/images/imoveis/imovel-8-13.jpg',
      '/images/imoveis/imovel-8-14.jpg',
      '/images/imoveis/imovel-8-15.png'
    ],
    isFeatured: true,
  },
  {
    id: '9',
    title: 'Chácara Locação',
    type: PropertyType.CASA,
    businessType: BusinessType.ALUGAR,
    price: 2000,
    location: { neighborhood: 'Zona Rural', city: 'São João da Boa Vista' },
    features: { bedrooms: 3, bathrooms: 2 },
    imageUrl: '/images/imoveis/aluguel-1-1.jpg',
    images: [
      '/images/imoveis/aluguel-1-1.jpg',
      '/images/imoveis/aluguel-1-2.jpg',
      '/images/imoveis/aluguel-1-3.jpg',
      '/images/imoveis/aluguel-1-4.jpg',
      '/images/imoveis/aluguel-1-5.jpg',
      '/images/imoveis/aluguel-1-6.jpg',
      '/images/imoveis/aluguel-1-7.jpg',
      '/images/imoveis/aluguel-1-8.jpg',
      '/images/imoveis/aluguel-1-9.jpg',
      '/images/imoveis/aluguel-1-10.jpg',
      '/images/imoveis/aluguel-1-11.jpg',
      '/images/imoveis/aluguel-1-12.jpg',
      '/images/imoveis/aluguel-1-13.jpg',
      '/images/imoveis/aluguel-1-14.jpg',
      '/images/imoveis/aluguel-1-15.png',
      '/images/imoveis/aluguel-1-16.jpg',
      '/images/imoveis/aluguel-1-17.jpg',
      '/images/imoveis/aluguel-1-18.jpg',
      '/images/imoveis/aluguel-1-19.jpg',
      '/images/imoveis/aluguel-1-20.jpg',
      '/images/imoveis/aluguel-1-21.jpg',
      '/images/imoveis/aluguel-1-22.jpg'
    ],
    isFeatured: true,
  },
  {
    id: '10',
    title: 'Terreno Locação',
    type: PropertyType.TERRENO,
    businessType: BusinessType.ALUGAR,
    price: 6000,
    location: { neighborhood: 'Zona Rural', city: 'São João da Boa Vista' },
    features: {},
    imageUrl: '/images/imoveis/aluguel-2-1.jpg',
     images: [
      '/images/imoveis/aluguel-2-1.jpg',
      '/images/imoveis/aluguel-2-2.jpg',
      '/images/imoveis/aluguel-2-3.jpg',
      '/images/imoveis/aluguel-2-4.jpg',
      '/images/imoveis/aluguel-2-5.jpg',
      '/images/imoveis/aluguel-2-6.jpg'
    ],
    isFeatured: false,
  },
  {
    id: '11',
    title: 'Chácara Aluguel',
    type: PropertyType.CASA,
    businessType: BusinessType.ALUGAR,
    price: 2600,
    location: { neighborhood: 'Zona Rural', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 2 },
    imageUrl: '/images/imoveis/aluguel-3-1.jpg',
    images: [
      '/images/imoveis/aluguel-3-1.jpg',
      '/images/imoveis/aluguel-3-2.jpg',
      '/images/imoveis/aluguel-3-3.jpg',
      '/images/imoveis/aluguel-3-4.png',
      '/images/imoveis/aluguel-3-5.jpg',
      '/images/imoveis/aluguel-3-6.jpg',
      '/images/imoveis/aluguel-3-7.png',
      '/images/imoveis/aluguel-3-8.jpg',
      '/images/imoveis/aluguel-3-9.png',
      '/images/imoveis/aluguel-3-10.jpg'
    ],
    isFeatured: true,
  },
  {
    id: '12',
    title: 'Chácara Cantinho da Paz',
    type: PropertyType.CASA,
    businessType: BusinessType.ALUGAR,
    price: 1000,
    location: { neighborhood: 'Estrada da Serra da Paulista', city: 'São João da Boa Vista' },
    features: { bedrooms: 2, bathrooms: 2 },
    imageUrl: '/images/imoveis/aluguel-4-1.png',
    images: [
      '/images/imoveis/aluguel-4-1.png',
      '/images/imoveis/aluguel-4-2.jpg',
      '/images/imoveis/aluguel-4-3.png',
      '/images/imoveis/aluguel-4-4.png',
      '/images/imoveis/aluguel-4-5.png',
      '/images/imoveis/aluguel-4-6.png',
      '/images/imoveis/aluguel-4-7.jpg',
      '/images/imoveis/aluguel-4-8.jpg',
      '/images/imoveis/aluguel-4-9.png',
      '/images/imoveis/aluguel-4-10.png',
      '/images/imoveis/aluguel-4-11.jpg',
      '/images/imoveis/aluguel-4-12.png',
      '/images/imoveis/aluguel-4-13.jpg',
      '/images/imoveis/aluguel-4-14.jpg',
      '/images/imoveis/aluguel-4-15.jpg',
      '/images/imoveis/aluguel-4-16.png',
      '/images/imoveis/aluguel-4-17.png',
      '/images/imoveis/aluguel-4-18.png',
      '/images/imoveis/aluguel-4-19.png',
      '/images/imoveis/aluguel-4-20.png',
      '/images/imoveis/aluguel-4-21.png',
      '/images/imoveis/aluguel-4-22.png',
      '/images/imoveis/aluguel-4-23.png',
      '/images/imoveis/aluguel-4-24.jpg',
      '/images/imoveis/aluguel-4-25.png',
      '/images/imoveis/aluguel-4-26.png',
      '/images/imoveis/aluguel-4-27.png',
      '/images/imoveis/aluguel-4-28.jpg'
    ],
    isFeatured: true,
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Ana Paula Mendes',
    city: 'São João da Boa Vista',
    text: 'A Renata foi essencial na compra do nosso primeiro imóvel. Sua visão técnica e segurança jurídica nos deram a tranquilidade que precisávamos para um investimento tão alto.',
  },
  {
    id: '2',
    name: 'Roberto Silveira',
    city: 'Campinas',
    text: 'Atendimento impecável e extremamente profissional. Encontramos o imóvel perfeito graças à curadoria estratégica da Renata.',
  }
];
 